// Code generated by Wire. DO NOT EDIT.
//go:build !wireinject
// +build !wireinject

package di

import (
	_ "github.com/lib/pq"
	"order-service/internal/api"
	"order-service/internal/api/handler"
	"order-service/internal/config"
	"order-service/internal/db"
	"order-service/internal/repository"
	"order-service/internal/service"
)

func InitializeAPI(cfg config.Config) (*http.Server, error) {
	sqlxDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	err = db.Migrate(sqlxDB)
	if err != nil {
		return nil, err
	}
	orderRepository := repository.NewOrderRepository(sqlxDB)
	orderService := service.NewOrderService(orderRepository)
	orderHandler := handler.NewOrderHandler(orderService)
	server := http.NewServer(orderHandler)
	return server, nil
}
