// Code generated by Wire. DO NOT EDIT.
//go:build !wireinject
// +build !wireinject

package di

import (
	_ "github.com/lib/pq"
	"api-gateway-service/internal/api"
	"api-gateway-service/internal/api/handler"
	"api-gateway-service/internal/config"
)

func InitializeAPI(cfg config.Config) (*http.Server, error) {
	orderHandler := handler.NewOrderHandler(cfg.OrderURL)
	productHandler := handler.NewProductHandler(cfg.ProductURL)
	paymentHandler := handler.NewPaymentHandler(cfg.PaymentURL)
	userHandler := handler.NewUserHandler(cfg.UserURL)
	server := http.NewServer(userHandler, orderHandler, productHandler, paymentHandler)
	return server, nil
}
