// Code generated by Wire. DO NOT EDIT.
//go:build !wireinject
// +build !wireinject

package di

import (
	_ "github.com/lib/pq"
	"payment-service/internal/api"
	"payment-service/internal/api/handler"
	"payment-service/internal/config"
	"payment-service/internal/db"
	"payment-service/internal/repository"
	"payment-service/internal/service"
)

func InitializeAPI(cfg config.Config) (*http.Server, error) {
	sqlxDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	err = db.Migrate(sqlxDB)
	if err != nil {
		return nil, err
	}
	paymentRepository := repository.NewPaymentRepository(sqlxDB)
	paymentService := service.NewPaymentService(paymentRepository)
	paymentHandler := handler.NewPaymentHandler(paymentService)
	server := http.NewServer(paymentHandler)
	return server, nil
}
